import JSZip from "jszip";
import { saveAs } from "file-saver";

export const exportProject = async () => {
  const zip = new JSZip();

  // Create folder structure for a generic Vite React project
  const src = zip.folder("src");
  if (!src) throw new Error("Failed to create src folder in ZIP");

  zip.file("package.json", JSON.stringify({
    name: "aethera-generated-project",
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "tsc -b && vite build",
      preview: "vite preview"
    },
    dependencies: {
      "react": "^18.3.1",
      "react-dom": "^18.3.1"
    },
    devDependencies: {
      "@vitejs/plugin-react-swc": "^3.5.0",
      "typescript": "^5.2.2",
      "vite": "^5.2.0"
    }
  }, null, 2));

  zip.file("vite.config.ts", `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'

export default defineConfig({
  plugins: [react()],
})
`);

  zip.file("index.html", `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Aethera Spark Generated App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`);

  src.file("main.tsx", `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`);

  src.file("index.css", `body { font-family: sans-serif; background: #000; color: #fff; margin: 0; padding: 0; }`);

  src.file("App.tsx", `export default function App() {
  return (
    <div style={{ display: 'flex', height: '100vh', alignItems: 'center', justifyContent: 'center', flexDirection: 'column' }}>
      <h1>Generated by Aethera Spark</h1>
      <p>Your neural UI is ready for deployment.</p>
    </div>
  )
}
`);

  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, "aethera-project.zip");
};
